name: Build and Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    uses: rcorra68/reusable-workflows/.github/workflows/publish-dotnet-cli.yml@main
    with:
      project_path: src/AvvisoScadenzaPatenti.Cli/AvvisoScadenzaPatenti.Cli.csproj
      runtimes: '["linux-x64", "win-x64"]'
      artifact_name: license-reminder
