name: Prepare Release

on:
  push:
    branches:
      - develop
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  prepare:
    uses: rcorra68/reusable-workflows/.github/workflows/prepare-release.yml@main
